### ISSUE TITLE
Passing in the accessors to a create call doesn't seem to work.

### ISSUE THREAD

**Issue by ghost** [tomash/globalize3_accessors#1]
Here's an excerpt from Rails 3

ruby-1.9.2-p180 :008 > s = State.create(:code => "OO", :country_code => "OO", :name_en => "english", :name_fr => "french")
 => #<State id: 76, code: "OO", country_code: "OO", created_at: "2011-07-19 21:10:24", updated_at: "2011-07-19 21:10:24"> 
ruby-1.9.2-p180 :009 > s = State.find(76)
 => #<State id: 76, code: "OO", country_code: "OO", created_at: "2011-07-19 21:10:24", updated_at: "2011-07-19 21:10:24"> 
ruby-1.9.2-p180 :010 > s.name_en
 => "french" 
ruby-1.9.2-p180 :011 > s.name_fr
 => "french"

**Comment by tomash** [comment]
hi,

i'm going to take this gem down after i've realized that @paneq already did a globalize3-working fork of my good old easy_globalize2_accessors. please try @paneq's gem:
https://github.com/paneq/easy_globalize3_accessors

**Comment by ghost** [comment]
Thanks!

## 

Patrick Paul-Hus
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
